<template>
  <div class="form-container">
    <div class="max-w-screen-lg m-auto space-y-8 my-8 text-sm font-light">
      <h1 class="text-center py-3 text-2xl font-medium app-text-color-primary">
        TERMS OF USE
      </h1>

      <div class="text-xs text-right text-[#000]">Last Updated: Jan 2022</div>

      <p class="text-xs text-[#86868b] font-light">
        These Terms and Conditions ("Agreement") read together with the Privacy
        Policy located at (" Privacy Policy"), are a legally binding agreement
        between the user ("User" or "you") and Olous ("Olous”, "we" or "us")
        providing, inter alia, the terms that govern your access to and use of
        the below:
      </p>

      <ul class="pl-5 text-xs text-[#86868b] font-light">
        <li>
          a. The Mobile Application running under the name of OLOUS (hereinafter
          referred to as the “App”) the holding company of which is VADCORE PVT.
          LTD, whether accessed or used from the mobile application (available
          on any platform)
        </li>
        <li class="pt-3">
          b. Any ancillary services provided by Olous in connection with the App
        </li>
      </ul>

      <p class="text-xs text-[#86868b] font-light">
        This document is an electronic record in terms of (i) Information
        Technology Act, 2000; (ii) the rules framed there under as applicable;
        and (iii) the amended provisions pertaining to electronic records in
        various statutes as amended by the Information Technology Act, 2000.
        This electronic record is generated by a computer system and does not
        require any physical or digital signatures.
      </p>

      <p class="text-xs text-[#86868b] font-light">
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules,
        2011 that require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of the Platform
      </p>

      <div>
        <b class="text-[#86868b]">NOTICE</b>

        <p class="p-3 text-xs text-[#86868b] font-light">
          Please Read These Terms & Conditions Carefully. By Accessing This App
          You Agree To Be Bound By The Terms & Conditions Stated Below. If You
          Do Not Agree To The Terms & Conditions Stated Below, Please Do Not
          Access This App. Olous Reserves The Right To Change, Modify Or Amend
          These Terms And Conditions Without Any Notice. Modifications May Be
          Posted Here, And You Are Deemed To Be Aware Of And Bound By Any
          Changes.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">LIMITATION OF LIABILITY </b>
        <div class="p-3 space-y-4 text-xs text-[#86868b] font-light">
          <p>
            In No Event Shall Olous Or Its Licensors, Suppliers, Or Vendors,
            Their Officers, Directors, Employees, Or Agents, Be Liable For Any
            Special, Incidental, Indirect, Or Consequential Damages Of Any Kind,
            Or For Any Damages Whatsoever Resulting From Loss Of Use, Data Or
            Profits, Whether Or Not Olous Has Been Advised Of Possibility Of The
            Damage, Arising Out Of Or In Connection With The Use Or Performance
            Of The App Or Applications Or Of Failure To Provide Services That
            You Order From Olous Or Its Affiliates, Including Without
            Limitation, Damages Arising From Mistake, Omission, Virus, Delay, Or
            Interruption Of Service. In No Event Shall Olous Be Liable Or
            Responsible For Any Damages Or Consequences Arising From Or Related
            To Your Inappropriate Or Unauthorized Use Of The App Or Its Content.
          </p>
          <p>
            You Specifically Acknowledge That Olous Shall Not Be Liable For User
            Submissions Or The Defamatory, Offensive, Or Illegal Conduct Of Any
            Third Party And That The Risk Of Harm Or Damage From The Foregoing
            Rests Entirely With You.
          </p>
          <p>
            You Specifically Acknowledge That In The Event Of A Loss/Damage
            Arising Out Of A Malfunction Of An Application, Olous Shall Not
            Under Any Circumstance, Be Liable To Pay Any Consequential And/Or
            Special Damage Or Compensation
          </p>
          <div>
            <p>
              You Acknowledge And Agree That You Will Not Dispute And/Or Hold Us
              Responsible For:
            </p>
            <ul class="p-3 pl-5 space-y-4 text-xs text-[#86868b] font-light">
              <li>
                I. Any Act That Is Not Our Obligation Under This Agreement.
              </li>
              <li>
                II. Any Disclosures Made By Us To Any Statutory Body Under Any
                Law.
              </li>
              <li>
                <p>III. Any Loss, Notional or Otherwise, Incurred Because Of</p>
                <ul class="p-3 pl-5 space-y-4">
                  <li>
                    A. Processing Of Instructions Authenticated By Your Login
                    Credentials.
                  </li>
                  <li>
                    B. Non-Availability Or Non-Accessibility Of The App,
                    Telephone(S), Or Office(S) Of Olous For Reasons Including
                    Those Beyond Olous's Control.
                  </li>
                  <li>
                    C. Any Inaccuracy Or Typographical Error On The App Or The
                    Mobile Application Or Any Written, E-Mail & SMS
                    Communication. We Will Not Be Liable For Such Inaccuracies
                    Or Errors.
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div>
        <b class="text-[#86868b]">INTERPRETATION</b>
        <div class="p-3 text-xs text-[#86868b] font-light">
          <p>
            In this Agreement, unless the context otherwise requires references
            to recitals, clauses and sub-clauses are to recitals, clauses and
            sub-clauses of this Agreement; headings are inserted for ease of
            reference only and are not to be used to define, interpret or limit
            any of the provisions of this Agreement; references to the singular
            number shall include references to the plural number and vice versa;
            words denoting one gender include all genders; any reference in this
            Agreement to a statutory provision includes that provision and any
            regulation made in pursuance thereof, as from time to time modified
            or re-enacted, whether before or after the date of this Agreement;
            and any reference to a time limit in this Agreement means the time
            limit set out in the relevant clause or sub-clause or such other
            time limit which may be mutually agreed by the parties in writing.
          </p>
        </div>
      </div>

      <div>
        <b class="text-[#86868b]">USER REQUIREMENTS </b>
        <ul
          class="p-3 pl-5 space-y-4 list-disc text-xs text-[#86868b] font-light"
        >
          <li>
            AGE : You must be 18 Years or above, or the legal age to form a
            binding contract in your jurisdiction if that age is greater than 18
            years of age, be a member or use the App and its Services.
          </li>
          <li>
            Membership or use of this App is void where prohibited by applicable
            law, and the right to access the App will be deemed to be revoked in
            such jurisdictions ab initio. By using the App and/or the Services,
            You represent and warrant that You have the right, authority, and
            capacity to enter into these Terms of Use and to abide by all of the
            terms and conditions set forth herein. You also represent and
            warrant to Olous that you will use App in a manner consistent with
            any and all applicable laws and regulations.
          </li>
          <li>
            This app has been developed to promote an ecosystem that is
            conducive to the growth of Construction and Real Estate domain. The
            user warrants that his/ her actions and information/ content that
            he/ she posts shall be within and relevant to the domain of
            Construction and Real Estate. OLOUS reserves right to block
            irrelevant content and furthermore suspend/ terminate user/s who do
            not conform to this.
          </li>
          <li>
            You must belong to the Construction and Real Estate Sector and shall
            only post such content on the App which is relevant to the domain of
            Construction and Real Estate Sector.
          </li>
        </ul>
      </div>

      <div class="space-y-4 text-xs text-[#86868b] font-light">
        <b class="text-[#86868b]">SERVICES</b>

        <p class="p-3">
          The App is a networking and knowledge sharing platform for
          Construction and Real Estate Industry held/owned by VADCORE PRIVATE
          LIMITED, which shall provide the users with a platform for networking
          and connecting with each other whereby the users shall be allowed to
          post and share knowledge on their timeline and to their network.
        </p>
        <p class="p-3">
          Use of the Service provides you with access to some or more aspects or
          functionality of the platform. Such access includes a limited,
          non-transferable, non-exclusive right to access the platform and your
          personal dashboard for your own personal purpose. Any other use, or
          use for data mining, use of spiders, crawlers, bots, etc. is excluded.
          You may not reverse engineer, decompile or disassemble the App or the
          Service, or create derivative works of the App or the Service provided
          on the platform.
        </p>
        <p class="p-3">
          We reserve the right to change the terms or specifications of any
          Services in our discretion, with or without prior written notice to
          the Users, by replacement of text of this Agreement or description of
          subscription plans on the App or by written notice to you. Any changes
          will take effect immediately unless otherwise stated in the notice of
          change. If any amendment is unacceptable to you, your only recourse is
          to terminate relations with OLOUS. Your continued use of the Services
          following our notice of change will constitute a binding acceptance of
          the Agreement, as amended.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">RIGHT TO USE SERVICES</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          OLOUS hereby grants you permission to use the Services and Olous
          solely as set forth in this Agreement and in the manner set forth on
          Olous. In the event of any conflict between the terms of this
          Agreement and the users, the terms of this Agreement shall prevail.
          Any use of the Services other than as set forth in this Agreement or
          in violation of any term of this Agreement will result in suspension
          or revocation of your use privileges in our sole discretion.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">CONTENT DISCLAIMER </b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You further understand that Olous is a public platform and when using
          Olous's Service, you will be exposed to Content and Submissions from a
          variety of sources, and that Olous is not responsible for the
          accuracy, usefulness, safety, or intellectual property rights of or
          relating to such Content, and that such Content is not the
          responsibility of Olous. You further understand and acknowledge that
          you may be exposed to Content that is inaccurate, offensive, indecent,
          or objectionable, and you agree to waive, and hereby do waive, any
          legal or equitable rights or remedies you have or may have against
          Olous with respect thereto, and agree to indemnify and hold Olous, its
          officers, directors, employees, agents, affiliates, and/or licensors,
          harmless to the fullest extent allowed by law regarding all matters
          related to your use of the Olous Service, including chat and other
          shared content.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">SUSPENSION OR TERMINATION OF SERVICES</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Notwithstanding anything stated or implied to the contrary in this
          Agreement, we may at any time, without derogating from our other
          rights under this Agreement, applicable law or otherwise, suspend or
          terminate any or all of the Services, effective immediately upon
          issuance of a written notice. Such suspension or termination may also
          apply, as the case may be, to specific jurisdictions, lines of
          business and otherwise or to a specific customer or a group of Users.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">THIRD PARTY SERVICES</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          We reserve the right to use third party service providers in the
          provisions of all or part of the Services including, but not limited
          to, hosting providers, payment processing services, information and
          communication services, analytics services, internet advertising
          platforms, advertising service providers and platforms. Where any of
          the aforementioned services are provided by third parties, the User
          may be subject to such third party's terms and conditions. We accept
          no responsibility for services provided by any third party.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">REGISTRATION AND ACCOUNT</b>
        <ul class="p-3 pl-5 space-y-4 list-disc text-[#86868b]">
          <li>
            <b class="text-[#86868b]">Use of the Services</b>
            <p class="text-xs text-[#86868b] font-light">
              You may use the Services as a registered user only. However, you
              may not use the Services, as a registered user if you are not of
              legal age to enter into a contract in your jurisdiction or if you
              do not have the authority to accept this Agreement.
            </p>
          </li>

          <li>
            <b class="text-[#86868b]">Acceptance</b>
            <p class="text-xs text-[#86868b] font-light">
              By using the Services, you accept the terms of this Agreement and
              you fully authorize us to obtain, process, store, use and transmit
              your personal data in accordance with our Privacy Policy, which
              forms an integral part of this Agreement.
            </p>
          </li>

          <li>
            <b class="text-[#86868b]"> Registration </b>
            <p class="text-xs text-[#86868b] font-light">
              To register as a User, you have to create a user account on the
              App by following registration procedures and instructions set
              forth therein. There is no cost charged by us to create a User
              account.
            </p>
          </li>
        </ul>
      </div>

      <div>
        <b class="text-[#86868b]">YOUR MEMBERSHIP ACCOUNT</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          In order to access the App, you will have to create an account. You
          may never use another's account without permission. When creating your
          account, you must provide accurate and complete information. You are
          solely responsible for the activity that occurs on your account, and
          you must keep your account password secure. You must notify OLOUS
          immediately of any breach of security or unauthorized use of your
          account. You will be liable for any use made of your account or
          password and the losses of OLOUS or others due to such unauthorized
          use. OLOUS will not be liable for your losses caused by any
          unauthorized use of your account.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          OLOUS has the right to refuse service, terminate accounts, terminate
          your access to the App, remove or edit content, or cancel orders in
          its sole discretion, immediately and with or without cause.
        </p>

        <ul class="p-3 pl-8 space-y-4 list-disc text-[#86868b]">
          <li>
            <b class="text-[#86868b]"> User Responsibilities</b>
            <p class="p-3 text-xs text-[#86868b] font-light">
              You are responsible for all of the following with respect to your
              use of the Services:
            </p>
            <ul class="space-y-3 pl-3 text-xs text-[#86868b] font-light">
              <li>
                a) maintaining the security of your User account and all the
                activity that occurs on your User account;
              </li>
              <li>
                b) maintaining accurate account information at all times,
                including a valid email address and updating such information as
                necessary;
              </li>
            </ul>
          </li>
        </ul>
      </div>

      <div>
        <b class="text-[#86868b]">Prohibited Uses</b>
        <div class="p-3 text-xs text-[#86868b] font-light">
          <p>
            You are expressly prohibited from using the Services in any of the
            following ways or for any of the following purposes:
          </p>
          <ul class="p-3 space-y-4">
            <li>
              <b>a) No Illegal Purpose.</b> You may not use the Services for any
              illegal or unauthorized purpose, including in any way that
              violates copyright or other applicable laws.
            </li>
            <li>
              <b>b) No Tampering.</b> You may not use the Services in a way that
              is detrimental to the operation of the Services or the access or
              use of the Services by anyone else. You will not upload or
              transmit viruses, worms or any other destructive code. The
              restriction in this Section applies to any use that interferes or
              attempts to interfere with the normal operations of the Services,
              including by hacking, deleting, augmenting or altering the
              Services.
            </li>
            <li>
              <b>c)Permission Required.</b> You may not, without our prior
              written permission and, solely with respect to lease, resale and
              sublicense, (i) copy, distribute (including by framing any of the
              Services on any web App), modify, enhance, translate, reproduce,
              sell, resell, sublicense, rent, lease, or otherwise attempt to
              exploit the Services or any data resulting therefrom; (ii)
              decompile, disassemble, reverse engineer, or otherwise attempt to
              discover the source code; (iii) make derivative works of the
              Services; (iv) remove, obscure, or alter any copyright notice,
              trademarks, or other proprietary rights notices affixed to or
              contained within or accessed in conjunction with or through the
              App or Services; (v) modify another App so as to falsely imply
              that it is associated with the Services, OLOUS or any other OLOUS
              products or services; or (vi) make the App or Services or any part
              thereof available to others in a service undertaking or
              outsourcing arrangement or for any other commercial time-sharing,
              data processing or other third party use.
            </li>
            <li>
              <b>d) Fake or Duplicate Accounts:</b> You are not allowed to
              create fake or duplicate accounts. In instances of such
              occurrence, we reserve right to suspend or delete such accounts
              without prior notice.
            </li>
          </ul>
        </div>
      </div>

      <div>
        <b class="text-[#86868b]">YOUR CONTENT</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You retain all rights and ownership in your content. Olous does not
          claim any ownership rights in your content.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Even though we don't claim ownership of your content, we do need
          certain licenses to your content in order to operate and enable the
          Services. When you upload or submit content to our Services, you grant
          Olous ( and our parents and affiliates ) a worldwide license to
          communicate, distribute, host, make modifications or derivative works
          (solely for the purpose of better showcase of your work), publicly
          display, publicly perform, publish, reproduce, store and use such
          content. The license granted by you is for the only purpose of
          operating, marketing, promoting, and improving our Services.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">YOUR STUFF AND PERMISSIONS </b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          When you use our Services, you provide us with things like your files,
          content, email messages, contacts and so on (“Your Stuff”), Your Stuff
          is yours. These terms don't give us any rights to use your Stuff
          except for the limited rights that enable us to offer the Services.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          We need your permission to do things like hosting Your Stuff, backing
          it up, and sharing it when you'd ask us to. Our Services also provide
          you with features like photo thumbnails, document previews, email
          organization, easy sorting, editing, sharing, and searching. These and
          other features might require our systems to access, store and scan
          Your Stuff. You give us permission to do those things, and this
          permission extends to our affiliates and trusted third parties we work
          with.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Additionally, the content and actions generated within the app by the
          users shall be used by Olous to collect information for the purpose of
          improving the app and for enhanced user experience and you hereby give
          us permission for the same.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">LINKS</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          The App may contain links to third party Apps or websites that are not
          owned or controlled by OLOUS. OLOUS is not affiliated with those Apps
          or websites, has no control over, and assumes no responsibility for,
          the content, privacy policies, or practices of any third-party Apps.
          In addition, OLOUS will not and cannot censor or edit the content of
          any third-party App. By using the App, you expressly release OLOUS
          from any and all liability arising from your use of any third-party
          App. Accordingly, we encourage you to be aware when you have left the
          App and to read the terms and conditions and privacy policy of each
          other App that you visit.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">YOUR OBLIGATIONS WHEN USING THIS APP </b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          OLOUS hereby grants you a limited license to use the materials,
          features, and services provided by OLOUS on this App (collectively the
          "Materials") solely for your personal, non-commercial use, subject to
          these Terms. The design and layout of the App are specifically
          excluded from the Materials. No other use of the App or Materials is
          authorized. You agree that any copy of the Materials (or any portion
          of the Materials) that you make must retain all copyright and other
          proprietary notices contained herein or therein. Framing of the App or
          App Materials or posting of Materials on other App is strictly
          prohibited.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          The products, technology, or processes described or used on this App
          may be the subject of intellectual property rights reserved by OLOUS
          or other third parties. Except for the limited license granted above,
          nothing contained herein confers to you in any manner, whether by
          implication, estoppel or otherwise, any license, title, or ownership
          of or to any intellectual property right of OLOUS or any third party.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">OUR LIABILITY TO YOU </b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          We provide the content on this App in good faith but give no warranty
          or representation that the content is accurate, complete or
          up-to-date, nor that this App does not infringe the rights of any
          third party. Except as permitted under the Product Terms, we accept no
          responsibility or liability for your use of content on this App and
          such use is entirely at your own risk. While we take reasonable
          precautions to prevent the existence of computer viruses and/or other
          malicious programs on this App, we cannot accept any liability for
          them.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Information transmitted via this App will pass over public
          telecommunications networks.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          This App may contain links to other Apps or websites. We accept no
          responsibility or liability for any material supplied by or contained
          on any third-party App which is linked from or to this App, or any use
          of personal data by such third party. We make no representation or
          warranty that the operation of this App will be uninterrupted or error
          free and disclaim all liabilities in respect thereof
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">RIGHT TO FILTER CONTENT:</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Olous shall have the ultimate say on what is allowed through the App
          and retains the right to review, delete or refuse to display content
          that violates laws or the terms and conditions for the usage of the
          App.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">ELECTRONIC COMMUNICATIONS</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          When you visit OLOUS or send e-mails to us, you are communicating with
          us electronically. You consent to receive communications from us
          electronically. We will communicate with you by e-mail or by posting
          notices on this App. You agree that all agreements, notices,
          disclosures and other communications that we provide to you
          electronically satisfy any legal requirement that such communications
          be in writing.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">PROMOTIONS/ADVERTISEMENT</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          If you use Olous to communicate or administer a promotion or advertise
          in any way, you are responsible for the lawful operation of that
          promotion or advertisement, including:
        </p>
        <ul class="pl-3 space-y-4 text-xs text-[#86868b] font-light">
          <li>a. Official rules</li>
          <li>b. Offer terms and eligibility requirements. And</li>
          <li>
            c. Compliance with applicable rules and regulations governing the
            promotion and all prizes offered
          </li>
        </ul>
      </div>

      <div>
        <b class="text-[#86868b]">INTELLECTUAL PROPERTY</b>
        <ul
          class="p-3 pl-5 space-y-4 list-disc text-xs text-[#86868b] font-light"
        >
          <li>
            All the data and information contained in services, the software
            used to operate it and the trademarks, logos, copyrights subsisting
            in its content along with any and all intellectual property used in
            connection with the App is the property of OLOUS. No license of any
            such intellectual property rights is granted to you as a result of
            your use of the services provided by Olous.
          </li>
          <li>
            All content included on the App, such as text, graphics, logos,
            button icons, images, audio clips, digital downloads, data
            compilations, and software, is the property of OLOUS or its content
            suppliers and protected by international copyright laws. The
            compilation of all content on this App is the exclusive property of
            OLOUS, with copyright authorship for this collection by OLOUS, and
            protected by international copyright laws.
          </li>
          <li>
            OLOUS's trademarks and trade name shall not be used in connection
            with any product or service that is not OLOUS's, in any manner that
            is likely to cause confusion among customers, or in any manner that
            disparages or discredits OLOUS. All other trademarks not owned by
            OLOUS or its subsidiaries that appear on this App are the property
            of their respective owners, who may or may not be affiliated with,
            connected to, or sponsored by OLOUS or its subsidiaries.
          </li>
          <li>
            All the Intellectual Property Rights are subject to protection as
            per the prevailing international laws
          </li>
        </ul>
      </div>

      <div>
        <b class="text-[#86868b]">ACCEPTABLE USE POLICY </b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          While OLOUS does not ordinarily monitor the content of users, it
          reserves the right to investigate reports of misuse of its service and
          to protect its property and assets. The following conduct is
          prohibited on the service:
        </p>
        <ul class="pl-3 space-y-4 text-xs text-[#86868b] font-light">
          <li>A. sending harassing, abusive, or threatening messages;</li>
          <li>B. sending obscene or pornographic messages or images;</li>
          <li>C. sending defamatory or libellous messages;</li>
          <li>
            D. sending viruses or other harmful, disruptive, or destructive
            files;
          </li>
          <li>E. attempting to steal passwords or credit card information;</li>
          <li>
            F. sending messages in furtherance of unlawful, criminal, or
            fraudulent activity; or
          </li>
          <li>
            G. attempting to conceal or misrepresent the identity of the sender.
          </li>
          <li>
            H. Collect or process special categories of personal data or
            personal data relating to criminal convictions and offences of EU
            citizens (as defined in the GDPR) other than in compliance with the
            provisions of applicable data protection law, including but not
            limited to the GDPR;
          </li>
        </ul>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Violations of the OLOUS's Acceptable Use Policy will not be tolerated
          and may result in the user being blocked from using the services of
          the App.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">SPAM</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You will only provide User Submitted Content that does not contain
          personally identifiable information about other persons, such as their
          phone number, contact information or email address, or information
          about that could result in an invasion of their privacy or their
          harassment.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You will only provide User Submitted Content that is not illegal,
          indecent, profane, threatening, obscene, abusive, hateful, or
          defamatory; and does not consist of or contain software viruses,
          political campaigning, commercial solicitation, chain letters, mass
          mailings or any form of "spam."
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You may not use this App to send unsolicited bulk or commercial
          messages. In addition, the use of automated scripting-type programs
          that automate the process of sending or viewing any of the Materials
          is strictly prohibited.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">INDEMNIFICATION</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You agree to defend, indemnify and hold harmless OLOUS, its
          affiliates, and their respective officers, directors, employees and
          agents, from and against any and all claims, damages, obligations,
          losses, liabilities, costs and expenses (including but not limited to
          attorney's fees) arising from:
        </p>
        <ul class="pl-5 space-y-4 text-xs text-[#86868b] font-light">
          <li>(i) your use of the Application(s)</li>
          <li>(ii) your violation of these Terms of Use</li>
          <li>
            (iii) your violation of the terms which apply to your User
            Submission
          </li>
          <li>
            (iv) your violation of any third-party right, including without
            limitation any copyright, property, publicity or privacy right; or
          </li>
          <li>
            (v) any claim that one of your User Submissions caused damage to a
            third party. This defence and indemnification obligation will
            survive these Terms of Use and your use of the App.
          </li>
        </ul>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You must cooperate as fully as reasonably required in defence of any
          such claim. OLOUS reserves the right, at its own expense, to assume
          the exclusive defence and control of any matter subject to
          indemnification by you.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">DISPUTES</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          The relationship between you and OLOUS shall be governed by the laws
          of the Republic of India without regard to its conflict of law
          provisions. All disputes are subject, firstly, to mediation, and then
          by Arbitration by a sole arbitrator appointed mutually by discussions
          between you and us. The venue of arbitration will be Pune, India. The
          Arbitrator's award shall be binding.
        </p>
        <p class="p-3 text-xs text-[#86868b] font-light">
          You and OLOUS agree to submit to the personal and exclusive
          jurisdiction of the courts located at Pune, India.
        </p>
      </div>

      <div>
        <b class="text-[#86868b]">QUESTIONS</b>
        <p class="p-3 text-xs text-[#86868b] font-light">
          Questions regarding our Conditions of Usage, Privacy Policy, or other
          policy related material can be directed to our support staff by
          clicking on the "Contact Us" link in the side menu. Or you can email
          us at:
          <a href="mailto:support@olous.app" class="text-[#d2d2d7]"
            >support@olous.app</a
          >
        </p>
      </div>
    </div>
  </div>
</template>
